version: "3.0"
services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  codegen:
    image: nginx
    environment:
      VIRTUAL_HOST: codegen.localhost
    volumes:
      - "./SwaggerGUI/dist/mat:/usr/share/nginx/html:ro"
      - "./docker/nginx:/etc/nginx/conf.d:ro"
  # dbgui:
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - db
  #   environment:
  #     VIRTUAL_HOST: dbgui.localhost
  #     PMA_HOST: db
  #     MYSQL_PASSWORD: ""
  #     MYSQL_USER: "root"
  # db:
  #   image: mariadb
  #   environment:
  #     VIRTUAL_HOST: db.localhost
  #     MYSQL_DATABASE: "eteam"
  #     MYSQL_USER: "root"
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  #   volumes:
  #     - ./docker/db:/var/lib/mysql
  # feg:
  #   build: ./AngularGlobal
  #   environment:
  #     VIRTUAL_HOST: feg.localhost
  #   volumes:
  #     - "/app/node_modules"
  #     - "./AngularGlobal:/app"
  # fec:
  #   build: ./AngularCompany
  #   environment:
  #     VIRTUAL_HOST: fec.localhost
  #   volumes:
  #     - "/app/node_modules"
  #     - "./AngularCompany:/app"
  # fe:
  #   build: ./AngularClient
  #   environment:
  #     VIRTUAL_HOST: fe.localhost
  #   volumes:
  #     - "/app/node_modules"
  #     - "./AngularClient:/app"
  # fei:
  #   build: ./AngularInterview
  #   environment:
  #     VIRTUAL_HOST: fei.localhost
  #   volumes:
  #     - "/app/node_modules"
  #     - "./AngularInterview:/app"
  # be:
  #   depends_on:
  #     - db
  #   build: ./Server
  #   environment:
  #     VIRTUAL_HOST: be.localhost
  #   working_dir: "/app"
  #   volumes:
  #     - "/app/node_modules"
  #     - "./Server:/app"
